// gcc flutter.c glfw3.dll flutter_engine.dll -lopengl32 -I. -o flutter_glfw -mwindows -s

#include <GLFW/glfw3.h>
#include <assert.h>
#include <embedder.h>
#include <sys/time.h>

static_assert(FLUTTER_ENGINE_VERSION == 1, "");

static const size_t kInitialWindowWidth = 800;
static const size_t kInitialWindowHeight = 600;

void GLFWcursorPositionCallbackAtPhase(GLFWwindow *window,
                                       FlutterPointerPhase phase, double x,
                                       double y) {
    FlutterPointerEvent event = {};
    event.struct_size = sizeof(event);
    event.phase = phase;
    event.x = x;
    event.y = y;
    event.timestamp = (size_t)(FlutterEngineGetCurrentTime() * 1000);
    FlutterEngineSendPointerEvent(glfwGetWindowUserPointer(window), &event, 1);
}

void GLFWcursorPositionCallback(GLFWwindow *window, double x, double y) {
    GLFWcursorPositionCallbackAtPhase(window, kMove, x, y);
}

void GLFWmouseButtonCallback(GLFWwindow *window, int key, int action,
                             int mods) {
    if (key == GLFW_MOUSE_BUTTON_1 && action == GLFW_PRESS) {
        double x, y;
        glfwGetCursorPos(window, &x, &y);
        GLFWcursorPositionCallbackAtPhase(window, kDown, x, y);
        glfwSetCursorPosCallback(window, GLFWcursorPositionCallback);
    }

    if (key == GLFW_MOUSE_BUTTON_1 && action == GLFW_RELEASE) {
        double x, y;
        glfwGetCursorPos(window, &x, &y);
        GLFWcursorPositionCallbackAtPhase(window, kUp, x, y);
        glfwSetCursorPosCallback(window, NULL);
    }
}

static void GLFWKeyCallback(GLFWwindow *window, int key, int scancode,
                            int action, int mods) {
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
        glfwSetWindowShouldClose(window, GLFW_TRUE);
    }
}

void GLFWwindowSizeCallback(GLFWwindow *window, int width, int height) {
    FlutterWindowMetricsEvent event = {};
    event.struct_size = sizeof(event);
    event.width = width;
    event.height = height;
    event.pixel_ratio = 1.0;
    FlutterEngineSendWindowMetricsEvent(glfwGetWindowUserPointer(window), &event);
}

#define MY_PROJECT "./flutter_assets"

bool make_current(void *userdata) {
    glfwMakeContextCurrent((GLFWwindow *)userdata);
    return true;
}
bool clear_current(void *userdata) {
    glfwMakeContextCurrent(NULL);
    return true;
}
bool present(void *userdata) {
    glfwSwapBuffers((GLFWwindow *)userdata);
    return true;
}
uint32_t fbo_callback(void *userdata) {
    return 0;
}

bool RunFlutter(void *window) {
    FlutterRendererConfig config = {};
    config.type = kOpenGL;
    config.open_gl.struct_size = sizeof(config.open_gl);
    config.open_gl.make_current = make_current;
    config.open_gl.clear_current = clear_current;
    config.open_gl.present = present;
    config.open_gl.fbo_callback = fbo_callback;

    FlutterProjectArgs args = {
        .struct_size = sizeof(FlutterProjectArgs),
        .assets_path = MY_PROJECT,  // This directory is generated by `flutter build bundle`
        .main_path__unused__ = NULL,
        .packages_path__unused__ = NULL,
        .icu_data_path = MY_PROJECT "/icudtl.dat",  // Find this in your bin/cache directory.
    };
    FlutterEngine engine = NULL;
    FlutterEngineResult result = FlutterEngineRun(FLUTTER_ENGINE_VERSION, &config,  // renderer
                                                  &args, window, &engine);
    assert(result == kSuccess && engine != NULL);

    glfwSetWindowUserPointer((GLFWwindow *)window, engine);

    GLFWwindowSizeCallback((GLFWwindow *)window, kInitialWindowWidth, kInitialWindowHeight);

    return true;
}

int main(int argc, const char *argv[]) {
    int result = glfwInit();
    assert(result == GLFW_TRUE);

    GLFWwindow *window = glfwCreateWindow(kInitialWindowWidth, kInitialWindowHeight,
                                          "Flutter", NULL, NULL);
    assert(window != NULL);

    bool runResult = RunFlutter(window);
    assert(runResult);

    glfwSetKeyCallback(window, GLFWKeyCallback);
    glfwSetWindowSizeCallback(window, GLFWwindowSizeCallback);
    glfwSetMouseButtonCallback(window, GLFWmouseButtonCallback);
    while (!glfwWindowShouldClose(window))
        glfwWaitEvents();
    glfwDestroyWindow(window);
    glfwTerminate();

    return 0;
}
